apiVersion: v2
name: kafka-ui
description: A Helm chart for kafka-UI
type: application
version: 1.5.3
appVersion: v1.4.2
icon: https://raw.githubusercontent.com/kafbat/kafka-ui/main/documentation/images/logo_new.png
